# Generated by Django 5.2.8 on 2025-12-19 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("category_image", models.ImageField(blank=True, null=True, upload_to="categories/")),
                (
                    "active_status",
                    models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sub_category_name", models.CharField(max_length=100, unique=True)),
                ("sub_category_image", models.ImageField(blank=True, null=True, upload_to="subcategories/")),
                (
                    "active_status",
                    models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subcategories", to="book.category"),
                ),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
                "db_table": "sub_category",
            },
        ),
    ]
