# Generated by Django 5.2.8 on 2025-12-19 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("book_image", models.ImageField(blank=True, null=True, upload_to="books/cover/")),
                ("isbn", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ("language", models.CharField(max_length=50)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("edition", models.CharField(blank=True, max_length=50, null=True)),
                ("digital_file", models.FileField(blank=True, null=True, upload_to="books/digital/")),
                ("preview_file", models.FileField(blank=True, null=True, upload_to="books/preview/")),
                ("digital_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("physical_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("has_physical_copy", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_read_only", models.BooleanField(default=True)),
                ("is_downloadable", models.BooleanField(default=False)),
                (
                    "active_status",
                    models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=10),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="books_author", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("category", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="book.category")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "book",
            },
        ),
    ]
