# Generated by Django 5.2.8 on 2026-01-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
