# Generated by Django 5.2.8 on 2026-01-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_book_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="download_type",
            field=models.CharField(choices=[("free", "Free"), ("paid", "Paid")], default="free", max_length=10),
        ),
    ]
