# Generated by Django 5.2.8 on 2026-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_book_download_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="short_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
