# Generated by Django 5.2.8 on 2026-01-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_category_short_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="short_name",
        ),
    ]
