# Generated by Django 5.2.8 on 2026-01-14 04:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book", "0002_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionalDiscount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("promotion_title", models.CharField(blank=True, max_length=255, null=True)),
                ("discount_amount", models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True)),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("priority", models.PositiveIntegerField(blank=True, default=0, null=True)),
                ("start_date", models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("discount_book", models.ManyToManyField(blank=True, null=True, related_name="discount_product", to="book.book")),
                (
                    "discount_category",
                    models.ManyToManyField(blank=True, null=True, related_name="discount_category", to="book.category"),
                ),
            ],
            options={
                "verbose_name": "Promotional Discount",
                "verbose_name_plural": "Promotional Discounts",
                "db_table": "promotional_discount_rule",
                "ordering": ["-id"],
            },
        ),
    ]
