# Generated by Django 5.2.8 on 2026-01-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_book"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionaldiscount",
            name="discount_book",
            field=models.ManyToManyField(blank=True, related_name="discount_product", to="book.book"),
        ),
        migrations.AlterField(
            model_name="promotionaldiscount",
            name="discount_category",
            field=models.ManyToManyField(blank=True, related_name="discount_category", to="book.category"),
        ),
    ]
