# Generated by Django 5.2.8 on 2026-01-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_cart_cartproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="cart",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cart_products_cart", to="order.cart"),
        ),
    ]
