# Generated by Django 5.2.8 on 2026-01-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_cartproduct_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
