# Generated by Django 5.2.8 on 2026-01-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_orderpayment_orderproduct_shippingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
