# Generated by Django 5.2.8 on 2026-01-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_invoice_id_order_shipping_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="card_brand",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="card_issuer",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="card_issuer_country",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="card_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
