# Generated by Django 5.2.8 on 2026-01-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_orderpayment_card_brand_orderpayment_card_issuer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
