# Generated by Django 5.2.8 on 2026-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_orderproduct_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="profit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
