# Generated by Django 5.2.8 on 2026-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_orderproduct_profit_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionaldiscount",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
