# Generated by Django 5.2.8 on 2026-01-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_promotionaldiscount_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotionaldiscount",
            name="description",
        ),
    ]
