# Generated by Django 5.2.8 on 2026-01-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("subscription_price", models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ("subscription_duration_days", models.IntegerField(default=7)),
                (
                    "active_status",
                    models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=10),
                ),
                (
                    "book_read_limit",
                    models.CharField(choices=[("Limited", "Limited"), ("Unlimited", "Unlimited")], default="Limited", max_length=100),
                ),
                (
                    "book_download_limit",
                    models.CharField(choices=[("Limited", "Limited"), ("Unlimited", "Unlimited")], default="Limited", max_length=100),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscription",
            },
        ),
    ]
