# Generated by Django 5.2.8 on 2026-01-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="max_book_download_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="max_book_read_limit",
            field=models.IntegerField(default=0),
        ),
    ]
