# Generated by Django 5.2.8 on 2026-01-03 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_book"),
        ("subscription", "0002_subscription_max_book_download_limit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_status",
                    models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=10),
                ),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("read_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_subscriptions", to="subscription.subscription"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_subscriptions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
                "db_table": "user_subscription",
            },
        ),
        migrations.CreateModel(
            name="UserSubscriptionBooks",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("read_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_subscription_books", to="book.book"
                    ),
                ),
                (
                    "user_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscription_books",
                        to="subscription.usersubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription Books",
                "verbose_name_plural": "User Subscription Books",
                "db_table": "user_subscription_books",
            },
        ),
    ]
