# Generated by Django 5.2.8 on 2026-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_usersubscription_usersubscriptionbooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="payment_status",
            field=models.CharField(choices=[("paid", "Paid"), ("unpaid", "Unpaid")], default="unpaid", max_length=10),
        ),
    ]
