# Generated by Django 5.2.8 on 2026-01-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_usersubscription_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid"), ("failed", "Failed")], default="unpaid", max_length=10
            ),
        ),
    ]
