# Generated by Django 5.2.8 on 2026-01-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_alter_usersubscription_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
