# Generated by Django 5.2.8 on 2026-01-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0006_usersubscription_is_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="usersubscriptionbooks",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
