# Generated by Django 5.2.8 on 2026-01-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0007_remove_usersubscription_is_paid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(blank=True, max_length=150, null=True)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed")], default="pending", max_length=20
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(choices=[("online", "Online"), ("cod", "Cash on Delivery")], default="online", max_length=20),
                ),
                ("raw_response", models.JSONField(blank=True, null=True)),
                (
                    "sub_book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_info",
                        to="subscription.usersubscriptionbooks",
                    ),
                ),
            ],
            options={
                "db_table": "book_payment",
            },
        ),
    ]
