# Generated by Django 5.2.8 on 2026-01-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0008_bookpayment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookpayment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="bookpayment",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="bookpayment",
            name="card_brand",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bookpayment",
            name="card_issuer",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bookpayment",
            name="card_issuer_country",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bookpayment",
            name="card_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="bookpayment",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="success", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="bookpayment",
            name="sub_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="book_payment_info", to="subscription.usersubscriptionbooks"
            ),
        ),
    ]
